[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "web", "--dev"]
watch = true

[tasks.release]
run_task = { name = ["build-release"] }

[tasks.build-release]
command = "wasm-pack"
args = ["build", "--target", "web"]
